import React, { useMemo, useState } from "react";
import { Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { Bell, Calendar, Check, ChevronRight, Circle, Clock, Lock, MessageCircle, Sparkles, Target } from "lucide-react-native";
import { OnboardingStep } from "./api";
import { useTheme } from "../settings/context";

type Props = { step: OnboardingStep; value: unknown; onChange: (value: unknown) => void; onAction?: (action: string) => void };
const iconFor = (name?: string) => ({ bell: Bell, calendar: Calendar, chat: MessageCircle, clock: Clock, target: Target, spark: Sparkles }[name || "spark"] || Sparkles);

export function OnboardingStepRenderer({ step, value, onChange, onAction }: Props) {
  const { colors } = useTheme();
  const config = step.config || {};
  const [text, setText] = useState(typeof value === "string" ? value : "");
  const options: string[] = config.options || [];
  const selected = Array.isArray(value) ? value : value === undefined || value === null ? [] : [value];
  const Icon = iconFor(config.icon);
  const select = (option: string) => {
    if (step.kind === "MULTI_SELECT") {
      const next = selected.includes(option) ? selected.filter((item) => item !== option) : [...selected, option];
      if (config.cap && next.length > config.cap) return;
      onChange(next);
    } else onChange(option);
  };

  if (step.kind === "SPLASH") return <View className="flex-1 items-center justify-center"><Sparkles color={colors.accent} size={56} /><Text className="mt-4 text-title-lg text-ink-primary">Embermate</Text></View>;
  if (["MESSAGE", "WELCOME", "COMPARE", "CHART", "PAYWALL_PRE", "REVEAL"].includes(step.kind)) return <View className="flex-1 justify-center"><View className="mb-6 h-14 w-14 items-center justify-center rounded-pill bg-accent-soft"><Icon color={colors.accent} size={28} /></View><Text className="text-title-lg text-ink-primary">{config.headline}</Text><Text className="mt-3 text-body text-ink-secondary">{config.sub}</Text>{step.kind === "COMPARE" && <View className="mt-8 flex-row gap-3"><View className="flex-1 rounded-lg bg-background-surface2 p-5"><Text className="text-stat text-ink-primary">1x</Text><Text className="mt-2 text-body-sm text-ink-secondary">Without Embermate</Text></View><View className="flex-1 rounded-lg bg-accent-soft p-5"><Text className="text-stat text-accent">2x</Text><Text className="mt-2 text-body-sm text-ink-secondary">With Embermate</Text></View></View>}{step.kind === "REVEAL" && <View className="mt-8 rounded-lg bg-background-surface p-5"><Text className="text-subtitle text-ink-primary">Starter plan</Text><Text className="mt-2 text-body-sm text-ink-secondary">Your plan is built from your answers and will be generated securely.</Text></View>}</View>;
  if (step.kind === "COMMIT") return <View className="flex-1 justify-center"><Text className="text-title-lg text-ink-primary">{config.headline}</Text><View className="mt-6 rounded-lg bg-background-surface p-5"><Text className="text-body text-ink-secondary">I'm committing to build a lasting habit because I want to follow through. When it gets hard, my AI coach has my back.</Text></View><Pressable className="mt-6 items-center rounded-pill bg-accent-soft px-5 py-4" onPress={() => onChange(true)}><Text className="text-body font-semibold text-accent">{value ? "Signed" : "Tap to sign"}</Text></Pressable></View>;
  if (step.kind === "LOADING") return <View className="flex-1 justify-center"><Text className="text-title-lg text-ink-primary">{config.headline}</Text><View className="mt-6 h-2 overflow-hidden rounded-pill bg-background-surface2"><View className="h-full w-2/3 rounded-pill bg-accent" /></View>{(config.steps || []).map((item: string) => <View key={item} className="mt-4 flex-row items-center"><Check color={colors.accent} size={18} /><Text className="ml-3 text-body text-ink-secondary">{item}</Text></View>)}</View>;
  if (step.kind === "DATE" || step.kind === "REFERRAL") return <View><Text className="text-title-lg text-ink-primary">{config.headline}</Text><Text className="mt-3 text-body text-ink-secondary">{config.sub}</Text><TextInput className="mt-8 rounded-md border border-border bg-background-surface px-4 py-4 text-body text-ink-primary" placeholder={step.kind === "DATE" ? "YYYY-MM-DD" : "Referral code"} placeholderTextColor={colors.inkTertiary} value={text} onChangeText={(next) => { setText(next); onChange(next); }} /></View>;
  if (step.kind === "SLIDER") return <View><Text className="text-title-lg text-ink-primary">{config.headline}</Text><View className="mt-8 rounded-lg bg-background-surface p-6"><Text className="text-subtitle text-accent">{(config.labels || [])[Number(value ?? config.default ?? 1)]}</Text><View className="mt-6 flex-row justify-between">{(config.labels || []).map((label: string, index: number) => <Pressable key={label} onPress={() => onChange(index)}><Circle color={Number(value ?? 1) === index ? colors.accent : colors.inkTertiary} fill={Number(value ?? 1) === index ? colors.accent : "transparent"} size={22} /><Text className="mt-2 text-caption text-ink-secondary">{label}</Text></Pressable>)}</View></View></View>;
  if (step.kind === "PERMISSION") return <View className="flex-1 justify-center"><View className="mb-6 h-14 w-14 items-center justify-center rounded-pill bg-accent-soft"><Icon color={colors.accent} size={28} /></View><Text className="text-title-lg text-ink-primary">{config.headline}</Text><Text className="mt-3 text-body text-ink-secondary">{config.sub}</Text><Pressable className="mt-8 rounded-pill bg-accent px-5 py-4" onPress={() => onAction?.("allow")}><Text className="text-center text-body font-semibold text-ink-inverse">{config.optional ? "Connect" : "Allow"}</Text></Pressable></View>;
  if (step.kind === "PAYWALL" || step.kind === "DISCOUNT") return <View><Text className="text-title-lg text-ink-primary">{config.headline}</Text><Text className="mt-3 text-body text-ink-secondary">{config.sub}</Text><View className="mt-8 rounded-lg bg-background-surface p-5"><Text className="text-subtitle text-ink-primary">{step.kind === "DISCOUNT" ? `${config.discountPercent}% off your first year` : "Choose your plan"}</Text><Text className="mt-2 text-body-sm text-ink-secondary">{step.kind === "PAYWALL" ? "No commitment — cancel anytime." : "A limited-time offer for your first year."}</Text></View><Pressable className="mt-6 rounded-pill bg-accent px-5 py-4" onPress={() => onAction?.(step.kind === "PAYWALL" ? "start" : "claim")}><Text className="text-center text-body font-semibold text-ink-inverse">{step.kind === "PAYWALL" ? "Start free trial" : "Claim discount"}</Text></Pressable>{step.kind === "PAYWALL" && <Pressable className="mt-3 rounded-pill px-5 py-4" onPress={() => onAction?.("decline")}><Text className="text-center text-body text-ink-secondary">Maybe later</Text></Pressable>}{step.kind === "DISCOUNT" && <Pressable className="mt-3 rounded-pill px-5 py-4" onPress={() => onAction?.("decline")}><Text className="text-center text-body text-ink-secondary">No thanks</Text></Pressable>}</View>;
  return <ScrollView showsVerticalScrollIndicator={false}><Text className="text-title-lg text-ink-primary">{config.headline}</Text><Text className="mt-3 text-body text-ink-secondary">{config.sub}</Text><View className="mt-8 gap-3">{options.map((option) => { const on = selected.includes(option); return <Pressable key={option} onPress={() => select(option)} className={`flex-row items-center rounded-md border px-4 py-4 ${on ? "border-accent bg-accent-soft" : "border-border bg-background-surface"}`}><Text className={`flex-1 text-body ${on ? "text-accent" : "text-ink-primary"}`}>{option}</Text>{on ? <Check color={colors.accent} size={20} /> : <ChevronRight color={colors.inkTertiary} size={20} />}</Pressable>; })}</View></ScrollView>;
}
