export const TIMELINE_DATA = [
  {
    id: "1",
    day: "Today",
    date: "Oct 26",
    status: "All habits crushed!",
    icon: "flame",
    iconColor: "#13ec5b",
    iconBg: "rgba(19, 236, 91, 0.2)",
    cardTitle: "Today",
    cardSubtitle: "All habits crushed!",
    percentage: "100%",
    isCurrent: true,
  },
  {
    id: "2",
    day: "Yesterday",
    date: "Oct 25",
    status: "Missed Meditation",
    icon: "happy", 
    iconColor: "#F59E0B",
    iconBg: "rgba(245, 158, 11, 0.2)",
    cardTitle: "Yesterday",
    cardSubtitle: "Missed Meditation",
    percentage: null,
  },
  {
    id: "3",
    day: "Thursday",
    date: "Oct 24",
    status: "Leg day complete",
    icon: "barbell", 
    iconColor: "#F59E0B",
    iconBg: "rgba(245, 158, 11, 0.2)",
    cardTitle: "Thursday",
    cardSubtitle: "Leg day complete",
    percentage: null,
  },
  {
    id: "4",
    day: "Wednesday",
    date: "Oct 23",
    status: "Rest day",
    icon: "moon", 
    iconColor: "#64748B", 
    iconBg: "rgba(100, 116, 139, 0.2)",
    cardTitle: "Wednesday",
    cardSubtitle: "Rest day",
    percentage: null,
  },
  {
    id: "5",
    day: "Tuesday",
    date: "Oct 22",
    status: "Read 20 pages",
    icon: "book",
    iconColor: "#EF4444", 
    iconBg: "rgba(239, 68, 68, 0.2)",
    cardTitle: "Tuesday",
    cardSubtitle: "Read 20 pages",
    percentage: null,
  },
];
